---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При оформлении заказа пользователь должен быть зарегистрирован и авторизован
  - При оформлении заказа у пользователя должны быть указаны контактные данные
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность продолжать покупки после перехода в корзину
  - Количество товара не может быть отрицательным числом
  - Количество товара не может быть дробным числом
  - В корзину нельзя положить товар, если его количсевто равно "0"
  - Цена товара не может быть равна "0" и быть отрицательным числом
